"""`vpsmcp set-password` writes the hash into the env file (hash-password only
prints it - the trap that made a "reset" a no-op). set_env_line does the surgical,
atomic replacement; here we prove it round-trips through the same env loader the
CLI and service use, including a password with shell-hostile characters like !.
"""
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from vpsmcp.auth.keys import hash_password, verify_password  # noqa: E402
from vpsmcp.setup import set_env_line  # noqa: E402
from vpsmcp.__main__ import _load_env_file  # noqa: E402

d = Path(tempfile.mkdtemp())
env = d / "vpsmcp.env"
env.write_text(
    "# generated by `vpsmcp setup`\n"
    "VPSMCP_PUBLIC_URL='https://mcp.example.com'\n"
    "VPSMCP_ADMIN_USER='ops'\n"
    "VPSMCP_ADMIN_PASSWORD_HASH='scrypt$32768$8$1$OLDSALT$OLDDK'\n"
    "VPSMCP_ENROLL_MODE='open'\n",
    encoding="utf-8",
)

# 1. replacing an existing key touches only that line
pw = "S3cret!with!bangs"          # ! would be mangled as a shell arg; fine here
action = set_env_line(env, "VPSMCP_ADMIN_PASSWORD_HASH", hash_password(pw))
assert action == "replaced", action
text = env.read_text()
assert text.count("VPSMCP_ADMIN_PASSWORD_HASH=") == 1, "duplicate hash lines"
assert "VPSMCP_PUBLIC_URL='https://mcp.example.com'" in text
assert "VPSMCP_ADMIN_USER='ops'" in text
assert "VPSMCP_ENROLL_MODE='open'" in text
assert "OLDSALT" not in text
print("1. replaced only the hash line; other settings and comments preserved")

# 2. the written hash round-trips through the real env loader and verifies the pw
os.environ.pop("VPSMCP_ADMIN_PASSWORD_HASH", None)
os.environ["VPSMCP_ENV_FILE"] = str(env)
_load_env_file()
loaded = os.environ["VPSMCP_ADMIN_PASSWORD_HASH"]
assert loaded.startswith("scrypt$32768$8$1$"), loaded
assert verify_password(pw, loaded), "loaded hash does not verify the password"
assert not verify_password("wrong", loaded)
print("2. loaded hash verifies the new password (incl. ! characters)")

# 3. adding when the key is absent
env2 = d / "fresh.env"
env2.write_text("VPSMCP_ADMIN_USER='ops'\n", encoding="utf-8")
assert set_env_line(env2, "VPSMCP_ADMIN_PASSWORD_HASH", hash_password(pw)) == "added"
assert "VPSMCP_ADMIN_PASSWORD_HASH=" in env2.read_text()
print("3. appends the hash line when it is missing")

# 4. collapses accidental duplicate lines to one
env3 = d / "dupe.env"
env3.write_text("VPSMCP_ADMIN_PASSWORD_HASH='a'\nVPSMCP_ADMIN_PASSWORD_HASH='b'\nX='y'\n",
                encoding="utf-8")
set_env_line(env3, "VPSMCP_ADMIN_PASSWORD_HASH", "z")
t3 = env3.read_text()
assert t3.count("VPSMCP_ADMIN_PASSWORD_HASH=") == 1 and "'z'" in t3 and "X='y'" in t3
print("4. collapses duplicate keys to a single line")

# 5. mode is preserved across the atomic replace
env.chmod(0o640)
set_env_line(env, "VPSMCP_ADMIN_PASSWORD_HASH", hash_password("another!one!here"))
assert (env.stat().st_mode & 0o777) == 0o640, oct(env.stat().st_mode)
print("5. file mode (0640) preserved across the rewrite")

print("\nall set-password checks passed")
