"""Reverse-proxy config generation, shared by `vpsmcp setup` and `vpsmcp caddyfile`."""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

CADDYFILE = "/etc/caddy/Caddyfile"


def render(*, host: str, upstream: str, mcp_path: str, email: str | None = None,
           log_file: str | None = None, lock_anthropic: bool = False,
           route53_zone: str | None = None,
           allow_cidrs: tuple[str, ...] = ()) -> str:
    parts: list[str] = [
        f"# generated by vpsmcp; re-run `vpsmcp caddyfile` instead of editing",
        f"# resource URL: https://{host}{mcp_path}  (enter this exact string in the client)",
        "",
    ]
    if email:
        parts += ["{", f"\temail {email}", "}", ""]
    parts += [f"https://{host} {{", "\tencode zstd gzip", ""]
    if route53_zone:
        parts += [
            "\t# DNS-01, for when port 80 is unavailable. Needs a custom build:",
            "\t#   xcaddy build --with github.com/caddy-dns/route53",
            "\t# Credentials come from the environment, not this file (it is 644):",
            "\t#   /etc/systemd/system/caddy.service.d/aws.conf  (chmod 600)",
            "\ttls {", "\t\tdns route53 {", f'\t\t\thosted_zone_id "{route53_zone}"',
            "\t\t\taccess_key_id {env.AWS_ACCESS_KEY_ID}",
            "\t\t\tsecret_access_key {env.AWS_SECRET_ACCESS_KEY}",
            "\t\t}", "\t}", "",
        ]
    parts += [
        f"\treverse_proxy {upstream} {{",
        "\t\t# MCP streams for a long time: no buffering, no timeouts",
        "\t\tflush_interval -1",
        "\t\ttransport http {", "\t\t\tread_timeout 0", "\t\t\twrite_timeout 0", "\t\t}",
        "\t}", "",
        "\theader {",
        '\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"',
        "\t\tX-Content-Type-Options nosniff",
        "\t\tReferrer-Policy no-referrer",
        "\t\t-Server",
        "\t}",
    ]
    if log_file:
        # Off by default: Caddy already logs to journald, and a log block pointing
        # at an unwritable directory makes the whole config fail to load while the
        # process still reports active.
        parts += ["", "\tlog {", f"\t\toutput file {log_file}", "\t\tformat json", "\t}"]
    if lock_anthropic:
        nets = " ".join(("160.79.104.0/21",) + tuple(allow_cidrs))
        parts += [
            "",
            "\t# API endpoints locked to the Anthropic egress range" +
            (" plus the networks you passed." if allow_cidrs else "."),
            "\t# /oauth/authorize, /oauth/login and /enroll/* are excluded: the first two",
            "\t# are opened by your browser, the last by new nodes from arbitrary IPs.",
            "\t# Do not enable this if you use Claude Code: it connects from your machine.",
            "\t# It also blocks every other client (Kimi, GLM, ...) unless its egress",
            "\t# range is added with --allow-cidr; there is no published range for those,",
            "\t# so leave this off if you use them.",
            "\t@locked {",
            f"\t\tpath {mcp_path}* /.well-known/* /oauth/token /oauth/register /oauth/revoke",
            f"\t\tnot remote_ip {nets}",
            "\t}",
            '\trespond @locked "forbidden" 403',
        ]
    parts += ["}", ""]
    return "\n".join(parts)


def installed() -> bool:
    return shutil.which("caddy") is not None


def write(content: str, path: str = CADDYFILE) -> tuple[bool, str]:
    """Write and validate; restore the previous file if validation fails."""
    p = Path(path)
    if not p.parent.is_dir():
        return False, f"{p.parent} does not exist; Caddy is not installed"
    backup = None
    if p.exists():
        backup = p.with_name(p.name + ".bak")
        backup.write_text(p.read_text(encoding="utf-8"), encoding="utf-8")
    p.write_text(content, encoding="utf-8")
    if installed():
        r = subprocess.run(["caddy", "validate", "--config", str(p), "--adapter", "caddyfile"],
                           capture_output=True, text=True)
        if r.returncode != 0:
            if backup:
                p.write_text(backup.read_text(encoding="utf-8"), encoding="utf-8")
            return False, (r.stderr or r.stdout).strip()[:500]
    return True, f"wrote {p}" + (f" (previous saved as {backup.name})" if backup else "")


def reload() -> tuple[bool, str]:
    if not installed():
        return False, "caddy is not installed"
    r = subprocess.run(["systemctl", "reload", "caddy"], capture_output=True, text=True)
    if r.returncode != 0:
        r = subprocess.run(["systemctl", "restart", "caddy"], capture_output=True, text=True)
    if r.returncode != 0:
        return False, (r.stderr or r.stdout).strip()[:300]
    return True, "reloaded"


def listening_443() -> bool:
    """active(running) does not mean the config loaded; check the port."""
    try:
        out = subprocess.run(["ss", "-ltn"], capture_output=True, text=True, timeout=5).stdout
    except Exception:  # noqa: BLE001
        return False
    return ":443 " in out


APT_INSTALL = r"""
apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
  | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
chmod o+r /usr/share/keyrings/caddy-stable-archive-keyring.gpg
chmod o+r /etc/apt/sources.list.d/caddy-stable.list
apt-get update -qq && apt-get install -y -qq caddy
"""


def apt_install() -> tuple[bool, str]:
    if installed():
        return True, "already installed"
    if os.geteuid() != 0:
        return False, "root required"
    r = subprocess.run(["bash", "-c", APT_INSTALL], capture_output=True, text=True)
    if not installed():
        return False, (r.stderr or r.stdout).strip()[-400:]
    return True, "installed"
