"""`vpsmcp setup`: configure, start and self-test the gateway in one command.

Everything needing precise quoting (.env, YAML, Caddyfile, SSH keys) is generated
in Python, never through a shell. The SSH key is created in-process.
"""
from __future__ import annotations

import getpass
import grp
import json
import os
import pwd
import secrets
import shutil
import socket
import string
import subprocess
import sys
import time
from pathlib import Path

import yaml

from . import caddy as caddymod
from .auth.keys import hash_password

ETC = Path("/etc/vpsmcp")
DATA = Path("/var/lib/vpsmcp")
APP = Path("/opt/vpsmcp")
ENVFILE = ETC / "vpsmcp.env"
KEY = ETC / "id_ed25519"
INVENTORY = ETC / "hosts.yaml"

C = {"b": "\033[1m", "g": "\033[32m", "y": "\033[33m", "r": "\033[31m", "d": "\033[90m", "x": "\033[0m"}


def say(m): print(f"{C['b']}==>{C['x']} {m}")
def ok(m): print(f"  {C['g']}✓{C['x']} {m}")
def warn(m): print(f"  {C['y']}!{C['x']} {m}")
def bad(m): print(f"  {C['r']}✗{C['x']} {m}")
def dim(m): print(f"  {C['d']}{m}{C['x']}")


# ---------------------------------------------------------------- helpers
def _chown(path: Path, user: str, group: str, mode: int) -> None:
    try:
        os.chown(path, pwd.getpwnam(user).pw_uid, grp.getgrnam(group).gr_gid)
    except (KeyError, PermissionError):
        pass
    try:
        path.chmod(mode)
    except OSError:
        pass


def _login_user() -> str:
    """Default admin is the invoking login user (SUDO_USER under sudo)."""
    for k in ("SUDO_USER", "LOGNAME", "USER"):
        v = os.environ.get(k)
        if v and v != "root":
            return v
    return "admin"


def _public_ip() -> str | None:
    import httpx
    for url in ("https://api.ipify.org", "https://ifconfig.me/ip"):
        try:
            r = httpx.get(url, timeout=6)
            if r.status_code == 200 and r.text.strip():
                return r.text.strip()
        except Exception:  # noqa: BLE001
            continue
    return None


def _resolve(host: str) -> list[str]:
    try:
        return sorted({i[4][0] for i in socket.getaddrinfo(host, None)})
    except OSError:
        return []


MIN_PASSWORD_LEN = 12


def prompt_admin_password(ask=getpass.getpass, notify=bad) -> str | None:
    """Interactively read the admin password, re-prompting on a rejected entry.

    A too-short password or a mismatched repeat used to abort the whole setup
    (`return 2`); now it just prints why and asks again. An empty entry returns
    None, meaning "generate one".
    """
    while True:
        p1 = ask("  admin password (empty = generate): ")
        if not p1:
            return None
        if len(p1) < MIN_PASSWORD_LEN:
            notify(f"password must be at least {MIN_PASSWORD_LEN} characters; try again")
            continue
        if p1 != ask("  repeat: "):
            notify("passwords do not match; try again")
            continue
        return p1


def gen_password(n: int = 20) -> str:
    alpha = string.ascii_letters + string.digits + "!@#%^&*-_=+"
    return "".join(secrets.choice(alpha) for _ in range(n))


def gen_ssh_key(path: Path, comment: str = "vpsmcp-gateway") -> str:
    """Generate an Ed25519 keypair in-process, write it out, return the public line."""
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    k = Ed25519PrivateKey.generate()
    priv = k.private_bytes(serialization.Encoding.PEM,
                           serialization.PrivateFormat.OpenSSH,
                           serialization.NoEncryption())
    pub = k.public_key().public_bytes(serialization.Encoding.OpenSSH,
                                      serialization.PublicFormat.OpenSSH).decode()
    pub_line = f"{pub} {comment}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(priv)
    path.chmod(0o600)
    path.with_suffix(path.suffix + ".pub").write_text(pub_line + "\n", encoding="utf-8")
    Path(str(path) + ".pub").chmod(0o644)
    return pub_line


def write_env(values: dict[str, str]) -> None:
    """Write .env. Values are single-quoted because the password hash contains $."""
    lines = ["# generated by `vpsmcp setup`", "", ]
    for k, v in values.items():
        lines.append(f"{k}='{str(v)}'" if "'" not in str(v) else f'{k}="{v}"')
    ENVFILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = ENVFILE.with_suffix(".env.tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(ENVFILE)
    _chown(ENVFILE, "root", "vpsmcp", 0o640)


def set_env_line(path: Path, key: str, value: str) -> str:
    """Replace (or append) `key='value'` in an env file, atomically, keeping every
    other line and the file's owner and mode. Returns 'replaced' or 'added'.

    Single-quoted because the scrypt hash contains `$`; the value never contains a
    single quote, so no escaping is needed. This is how `set-password` actually
    applies a new hash - `hash-password` only prints one, which is easy to forget
    to paste in.
    """
    import stat as _stat

    lines: list[str] = []
    replaced = False
    if path.exists():
        for ln in path.read_text(encoding="utf-8").splitlines():
            stripped = ln.lstrip()
            head = stripped.split("=", 1)[0].rstrip() if "=" in stripped else ""
            if head == key and not stripped.startswith("#"):
                if not replaced:            # replace the first, drop any duplicates
                    lines.append(f"{key}='{value}'")
                    replaced = True
            else:
                lines.append(ln)
    if not replaced:
        lines.append(f"{key}='{value}'")
    data = "\n".join(lines) + "\n"

    st = path.stat() if path.exists() else None
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(data, encoding="utf-8")
    if st is not None:
        try:
            os.chown(tmp, st.st_uid, st.st_gid)
        except (PermissionError, OSError):
            pass
        os.chmod(tmp, _stat.S_IMODE(st.st_mode))
    else:
        _chown(tmp, "root", "vpsmcp", 0o640)
    tmp.replace(path)
    return "replaced" if replaced else "added"


def read_env() -> dict[str, str]:
    out: dict[str, str] = {}
    if not ENVFILE.exists():
        return out
    try:
        for line in ENVFILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                out[k.strip()] = v.strip().strip("'").strip('"')
    except PermissionError:
        pass
    return out


# ---------------------------------------------------------------- self-test
def selftest(public_url: str, mcp_path: str, bind: str, timeout: int = 30) -> int:
    """Verify the path a client takes. Returns the failure count."""
    import httpx

    resource = public_url.rstrip("/") + mcp_path
    fails = 0
    say("self-test")

    # local first
    deadline = time.time() + timeout
    local = f"http://{bind}/healthz"
    while time.time() < deadline:
        try:
            r = httpx.get(local, timeout=3)
            if r.status_code == 200:
                ok(f"local /healthz  {r.text.strip()[:90]}")
                break
        except Exception:  # noqa: BLE001
            pass
        time.sleep(1)
    else:
        bad(f"{local} not responding; skipping public checks")
        dim("  journalctl -u vpsmcp -n 40")
        return 1

    if caddymod.installed():
        if caddymod.listening_443():
            ok("Caddy listening on 443")
        else:
            bad("Caddy is not listening on 443; its config likely failed to load")
            fails += 1

    checks = [
        ("public /healthz", f"{public_url}/healthz", lambda r: r.status_code == 200),
        ("protected resource metadata", f"{public_url}/.well-known/oauth-protected-resource{mcp_path}",
         lambda r: r.status_code == 200 and r.json().get("resource") == resource),
        ("authorization server metadata", f"{public_url}/.well-known/oauth-authorization-server",
         lambda r: r.status_code == 200
         and "S256" in (r.json().get("code_challenge_methods_supported") or [])),
        # clients that treat the resource URL as the issuer look here (RFC 8414)
        ("authorization server metadata (path form)",
         f"{public_url}/.well-known/oauth-authorization-server{mcp_path}",
         lambda r: r.status_code == 200 and r.json().get("issuer") == public_url),
    ]
    with httpx.Client(timeout=10, follow_redirects=False) as c:
        for name, url, pred in checks:
            try:
                r = c.get(url)
                if pred(r):
                    ok(name)
                else:
                    bad(f"{name}  HTTP {r.status_code}  {r.text[:120]}")
                    fails += 1
            except Exception as exc:  # noqa: BLE001
                bad(f"{name}  {exc}")
                fails += 1
        try:
            r = c.post(resource, json={"jsonrpc": "2.0", "id": 1, "method": "initialize"},
                       headers={"accept": "application/json, text/event-stream"})
            wa = r.headers.get("www-authenticate", "")
            if r.status_code == 401 and "resource_metadata=" in wa:
                ok("MCP endpoint: 401 with resource_metadata")
            else:
                bad(f"MCP endpoint: expected 401 with resource_metadata, got {r.status_code}")
                fails += 1
        except Exception as exc:  # noqa: BLE001
            bad(f"MCP endpoint  {exc}")
            fails += 1
    return fails


# ---------------------------------------------------------------- main
def run(argv: list[str]) -> int:
    if os.geteuid() != 0:
        print("run with sudo: sudo vpsmcp setup", file=sys.stderr)
        return 1

    def flag(n): return n in argv
    def opt(n, d=""):
        return argv[argv.index(n) + 1] if n in argv and argv.index(n) + 1 < len(argv) else d

    yes = flag("-y") or flag("--yes") or flag("--non-interactive")
    tty = sys.stdin.isatty() and not yes
    existing = read_env()

    def ask(prompt: str, default: str = "") -> str:
        if not tty:
            return default
        s = input(f"  {prompt}" + (f" [{default}]" if default else "") + ": ").strip()
        return s or default

    print(f"\n{C['b']}vpsmcp gateway setup{C['x']}\n")

    # ---- domain ----
    domain = opt("--domain") or existing.get("VPSMCP_PUBLIC_URL", "").replace("https://", "")
    if not domain:
        domain = ask("public domain (e.g. mcp.example.com)")
    domain = domain.replace("https://", "").replace("http://", "").strip("/")
    if not domain or "." not in domain:
        bad("a domain is required: --domain mcp.example.com")
        return 2

    admin_user = opt("--admin-user") or existing.get("VPSMCP_ADMIN_USER") or _login_user()
    if tty and not opt("--admin-user"):
        admin_user = ask("admin username", admin_user)
    email = opt("--email") or f"admin@{'.'.join(domain.split('.')[-2:])}"
    mcp_path = "/" + (opt("--mcp-path", "mcp").strip("/") or "mcp")
    bind_host, bind_port = "127.0.0.1", opt("--port", "8848")

    # ---- password ----
    password = opt("--password")
    generated = False
    if not password and tty:
        password = prompt_admin_password()
    if not password:
        password = gen_password()
        generated = True

    # ---- accounts and directories ----
    say("accounts and directories")
    subprocess.run(["useradd", "--system", "--home", str(APP), "--shell",
                    "/usr/sbin/nologin", "vpsmcp"], capture_output=True)
    for d, u, g, m in ((APP, "vpsmcp", "vpsmcp", 0o750), (DATA, "vpsmcp", "vpsmcp", 0o750),
                       (ETC, "root", "vpsmcp", 0o750)):
        d.mkdir(parents=True, exist_ok=True)
        _chown(d, u, g, m)
    ok(f"{ETC}  {DATA}  {APP}")

    # ---- SSH key ----
    pubpath = Path(str(KEY) + ".pub")
    if KEY.exists():
        import asyncssh
        try:
            k = asyncssh.read_private_key(str(KEY))
        except Exception as exc:  # noqa: BLE001
            bad(f"{KEY} exists but cannot be read: {exc}")
            dim("not regenerating: a new key would orphan every enrolled node")
            dim(f"if nothing depends on it, rm {KEY}* and re-run; otherwise restore a backup")
            return 2
        pub_line = k.export_public_key("openssh").decode().strip()
        if not pub_line.split()[-1].startswith("vpsmcp"):
            pub_line += " vpsmcp-gateway"
        pubpath.write_text(pub_line + "\n", encoding="utf-8")
        ok("reusing the existing gateway key")
    else:
        pub_line = gen_ssh_key(KEY)
        ok("generated an Ed25519 gateway keypair")
        # A fresh key orphans nodes enrolled with the previous one.
        stale = sorted(q.stem for q in (ETC / "hosts.d").glob("*.yaml")) if (ETC / "hosts.d").is_dir() else []
        if stale:
            warn(f"{len(stale)} node(s) were enrolled with the old key: {', '.join(stale)}")
            dim("they are unreachable now; remove each, then re-run the enroll installer on that node:")
            for a in stale:
                dim(f"    sudo vpsmcp node remove {a}")
    # root-owned, group-readable: the service reads it but cannot overwrite it
    _chown(KEY, "root", "vpsmcp", 0o640)
    _chown(pubpath, "root", "vpsmcp", 0o644)
    if shutil.which("ssh-keygen"):
        fp = subprocess.run(["ssh-keygen", "-lf", str(KEY) + ".pub"],
                            capture_output=True, text=True).stdout.split()
        dim(f"fingerprint {fp[1] if len(fp) > 1 else '?'}")

    # ---- inventory ----
    if not INVENTORY.exists():
        INVENTORY.write_text(yaml.safe_dump(
            {"defaults": {"user": "ops", "port": 22}, "hosts": []},
            allow_unicode=True, sort_keys=False), encoding="utf-8")
        ok("created an empty hosts.yaml")
    _chown(INVENTORY, "root", "vpsmcp", 0o640)
    (ETC / "known_hosts").touch()
    _chown(ETC / "known_hosts", "root", "vpsmcp", 0o644)
    # /etc/vpsmcp stays root-owned so the service cannot touch the key or .env;
    # only hosts.d is writable by it.
    hd = ETC / "hosts.d"
    hd.mkdir(exist_ok=True)
    _chown(hd, "vpsmcp", "vpsmcp", 0o750)
    ok("hosts.d is writable by the service")

    # ---- .env ----
    env = {
        "VPSMCP_PUBLIC_URL": f"https://{domain}",
        "VPSMCP_MCP_PATH": mcp_path,
        "VPSMCP_BIND_HOST": bind_host,
        "VPSMCP_BIND_PORT": bind_port,
        "VPSMCP_DATA_DIR": str(DATA),
        "VPSMCP_INVENTORY": str(INVENTORY),
        "VPSMCP_AUDIT_LOG": str(DATA / "audit.jsonl"),
        "VPSMCP_SSH_KEY": str(KEY),
        "VPSMCP_KNOWN_HOSTS": str(ETC / "known_hosts"),
        "VPSMCP_STRICT_HOST_KEYS": "1",
        "VPSMCP_ADMIN_USER": admin_user,
        # which MCP clients may complete a login; see `vpsmcp clients`
        "VPSMCP_CLIENTS": existing.get("VPSMCP_CLIENTS", "claude,local,kimi,glm"),
        "VPSMCP_ADMIN_PASSWORD_HASH": existing.get("VPSMCP_ADMIN_PASSWORD_HASH", ""),
        "VPSMCP_ENROLL_MODE": existing.get("VPSMCP_ENROLL_MODE", "open"),
        "VPSMCP_ENROLL_KEY": existing.get("VPSMCP_ENROLL_KEY", ""),
        "VPSMCP_ENROLL_ALLOW_CIDRS": existing.get("VPSMCP_ENROLL_ALLOW_CIDRS", ""),
        "VPSMCP_ENROLL_USER": existing.get("VPSMCP_ENROLL_USER", "ops"),
        "VPSMCP_ENROLL_SCOPES": existing.get("VPSMCP_ENROLL_SCOPES", "fleet.read,fleet.exec,fleet.write"),
        "VPSMCP_ENABLE_GUARDRAILS": "1",
        "VPSMCP_READ_ONLY": "0",
    }
    if password:
        env["VPSMCP_ADMIN_PASSWORD_HASH"] = hash_password(password)
    if not env["VPSMCP_ADMIN_PASSWORD_HASH"]:
        bad("no password hash; pass --password")
        return 2
    write_env(env)
    ok(f"wrote {ENVFILE}")
    return _finish(domain, mcp_path, bind_host, bind_port, email, admin_user,
                   password if generated else None, argv, flag)


def _proxy_systemd_unit() -> str:
    """Optional egress forward proxy. Installed but not enabled by setup; turn it
    on with `sudo vpsmcp proxy-password` + `systemctl enable --now vpsmcp-proxy`."""
    return f"""[Unit]
Description=VPS Fleet MCP egress proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
User=vpsmcp
Group=vpsmcp
EnvironmentFile={ENVFILE}
WorkingDirectory={APP}
ExecStart={APP}/.venv/bin/python -m vpsmcp proxy
Restart=always
RestartSec=3

NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
RestrictRealtime=yes
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
CapabilityBoundingSet=
ReadOnlyPaths={ETC}
UMask=0077
LimitNOFILE=8192
MemoryMax=256M

[Install]
WantedBy=multi-user.target
"""


def _systemd_unit() -> str:
    return f"""[Unit]
Description=VPS Fleet MCP Gateway
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
User=vpsmcp
Group=vpsmcp
EnvironmentFile={ENVFILE}
WorkingDirectory={APP}
ExecStart={APP}/.venv/bin/python -m vpsmcp serve
Restart=always
RestartSec=3

NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
CapabilityBoundingSet=
ReadWritePaths={DATA} {ETC}/hosts.d
ReadOnlyPaths={ETC}
UMask=0077
LimitNOFILE=8192
MemoryMax=512M

[Install]
WantedBy=multi-user.target
"""


def _finish(domain, mcp_path, bind_host, bind_port, email, admin_user,
            generated_password, argv, flag) -> int:
    def warn_local(m): warn(m)
    public_url = f"https://{domain}"
    bind = f"{bind_host}:{bind_port}"

    # ---- DNS ----
    say("DNS")
    ips = _resolve(domain)
    mine = _public_ip()
    if not ips:
        warn(f"{domain} does not resolve; add an A record to {mine or 'this host'} "
             f"or the certificate cannot be issued")
    elif mine and mine not in ips:
        warn(f"{domain} resolves to {', '.join(ips)} but this host is {mine}; "
             f"certificate issuance will fail")
    else:
        ok(f"{domain} → {', '.join(ips)}")
    if any(":" in i for i in ips):
        warn("AAAA record present: broken IPv6 causes intermittent failures")

    # ---- systemd ----
    say("systemd unit")
    Path("/etc/systemd/system/vpsmcp.service").write_text(_systemd_unit(), encoding="utf-8")
    # Egress proxy unit is installed but left disabled; enable it only after
    # `vpsmcp proxy-password` sets a credential.
    Path("/etc/systemd/system/vpsmcp-proxy.service").write_text(
        _proxy_systemd_unit(), encoding="utf-8")
    have_systemd = Path("/run/systemd/system").is_dir()
    if not have_systemd:
        warn("not booted with systemd (container?); unit written but not started")
        dim(f"run manually: {APP}/.venv/bin/python -m vpsmcp serve")
    else:
        subprocess.run(["systemctl", "daemon-reload"], capture_output=True)
        subprocess.run(["systemctl", "enable", "vpsmcp"], capture_output=True)
        subprocess.run(["systemctl", "restart", "vpsmcp"], capture_output=True)
        time.sleep(2)
        st = subprocess.run(["systemctl", "is-active", "vpsmcp"],
                            capture_output=True, text=True).stdout.strip()
        if st == "active":
            ok("vpsmcp service active")
        else:
            bad(f"vpsmcp service {st or 'failed to start'} - journalctl -u vpsmcp -n 40")

    # ---- Caddy ----
    if not flag("--no-caddy"):
        say("reverse proxy")
        if not caddymod.installed():
            dim("installing Caddy...")
            good, msg = caddymod.apt_install()
            (ok if good else bad)(f"Caddy {msg}")
        if caddymod.installed():
            allow_cidrs = tuple(argv[i + 1] for i, a in enumerate(argv)
                                if a == "--allow-cidr" and i + 1 < len(argv))
            conf = caddymod.render(host=domain, upstream=bind, mcp_path=mcp_path, email=email,
                                   lock_anthropic=flag("--lock-anthropic"),
                                   allow_cidrs=allow_cidrs)
            good, msg = caddymod.write(conf)
            (ok if good else bad)(msg)
            if good:
                good, msg = caddymod.reload()
                (ok if good else bad)(f"Caddy {msg}")
    else:
        warn("--no-caddy: configure the reverse proxy yourself")

    # ---- self-test ----
    fails = selftest(public_url, mcp_path, bind)

    # ---- optional: enroll the gateway itself ----
    if flag("--self-enroll"):
        say("enrolling the gateway as a node")
        url = f"http://{bind_host}:{bind_port}/enroll/install.sh"
        r = subprocess.run(["bash", "-c",
                            f"curl -sSf '{url}' | bash -s -- --alias gw --tags gateway,infra "
                            f"--user gwops"], capture_output=True, text=True)
        (ok if r.returncode == 0 else bad)(
            "gateway enrolled as a node" if r.returncode == 0
            else f"enrollment failed: {(r.stdout + r.stderr).strip()[-200:]}")

    # ---- summary ----
    print()
    if generated_password:
        print(f"{C['b']}Admin password (shown once - save it now){C['x']}")
        print(f"    username  {admin_user}")
        print(f"    password  {generated_password}\n")
    print(f"{C['b']}Add a custom MCP connector with this URL:{C['x']}")
    print(f"    {public_url}{mcp_path}")
    dim("Claude: Settings -> Connectors. Kimi and GLM: add an MCP server with the")
    dim("same URL, sign in on the page it opens, then approve the scopes.")
    dim("`sudo vpsmcp clients` lists the clients accepted; if one is turned away")
    dim("because of its callback URL, `sudo vpsmcp redirects` prints it.\n")
    print(f"{C['b']}Enroll a node (run on the target machine):{C['x']}")
    print(f"    curl -sSf {public_url}/enroll/install.sh | sudo bash")
    print(f"    curl -sSf {public_url}/enroll/install.sh | sudo bash -s -- --alias web-01 --tags prod\n")
    if fails:
        print(f"{C['y']}{fails} self-test check(s) failed{C['x']} - usually DNS not "
              f"propagated yet, or ports 80/443 blocked by a firewall.")
        print("    re-run after fixing: sudo vpsmcp setup --domain " + domain + " -y")
    else:
        print(f"{C['g']}All checks passed.{C['x']}")
    return 0 if fails == 0 else 1
